ProductSource:
  class_uri: https://openminds.ebrains.eu/chemicals/ProductSource
  description: Structured information about the source of a chemical substance or
    mixture.
  slot_usage:
    digitalIdentifier:
      range: RRID
    identifier:
      range: string
    productName:
      range: string
      required: true
    provider:
      required: true
    purity:
      inlined: true
  slots:
  - id
  - digitalIdentifier
  - identifier
  - productName
  - provider
  - purity
  title: Product source
