ProductSource:
  class_uri: https://openminds.ebrains.eu/chemicals/ProductSource
  description: Structured information about the source of a chemical substance or
    mixture.
  slot_usage:
    digitalIdentifier:
      range: RRID
    productName:
      required: true
    provider:
      required: true
    purity:
      any_of:
      - range: QuantitativeValue
      - range: QuantitativeValueRange
  slots:
  - id
  - digitalIdentifier
  - identifier
  - productName
  - provider
  - purity
  title: Product source
