Project:
  class_uri: https://openminds.ebrains.eu/core/Project
  description: Structured information on a research project.
  slot_usage:
    description:
      range: string
      required: true
    fullName:
      range: string
      required: true
    hasResearchProducts:
      list_elements_unique: true
      multivalued: true
      range: Dataset
      required: true
    homepage:
      range: string
    projectLeader:
      list_elements_unique: true
      multivalued: true
      range: Organization
    shortName:
      range: string
      required: true
  slots:
  - id
  - description
  - fullName
  - hasResearchProducts
  - homepage
  - projectLeader
  - shortName
  title: Project
