Project:
  attributes:
    description:
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/description
    fullName:
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/fullName
    hasResearchProducts:
      list_elements_unique: true
      multivalued: true
      range: Dataset
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/hasResearchProducts
    homepage:
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/homepage
    id:
      identifier: true
      required: true
      slot_uri: schema:identifier
    projectLeader:
      list_elements_unique: true
      multivalued: true
      range: Organization
      slot_uri: https://openminds.ebrains.eu/vocab/projectLeader
    shortName:
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/shortName
  class_uri: https://openminds.ebrains.eu/core/Project
  description: Structured information on a research project.
