productAccessibility:
  class_uri: https://openminds.ebrains.eu/controlledTerms/productAccessibility
  description: null
  slot_usage:
    definition:
      range: string
    description:
      range: string
    name:
      range: string
      required: true
    ontologyIdentifier:
      range: string
  slots:
  - id
  - definition
  - description
  - name
  - ontologyIdentifier
  title: Product accessibility
