Project:
  class_uri: https://openminds.ebrains.eu/core/Project
  description: Structured information on a research project.
  slot_usage:
    coordinator:
      range: Organization
    description:
      required: true
    fullName:
      required: true
    hasResearchProducts:
      range: Dataset
      required: true
    shortName:
      required: true
  slots:
  - id
  - coordinator
  - description
  - fullName
  - hasResearchProducts
  - homepage
  - shortName
  title: Project
