Environment:
  class_uri: https://openminds.ebrains.eu/computation/Environment
  description: Structured information on the computer system or set of systems in
    which a computation is deployed and executed.
  slot_usage:
    configuration:
      range: Configuration
    description:
      range: string
    hardware:
      required: true
    name:
      range: string
      required: true
    software:
      list_elements_unique: true
      multivalued: true
  slots:
  - id
  - configuration
  - description
  - hardware
  - name
  - software
  title: Environment
