Environment:
  attributes:
    configuration:
      range: Configuration
      slot_uri: https://openminds.ebrains.eu/vocab/configuration
    description:
      description: Longer statement or account giving the characteristics of someone
        or something.
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/description
    hardware:
      range: HardwareSystem
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/hardware
    id:
      identifier: true
      required: true
      slot_uri: schema:identifier
    name:
      description: Word or phrase that constitutes the distinctive designation of
        a being or thing.
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/name
    software:
      list_elements_unique: true
      multivalued: true
      range: SoftwareVersion
      slot_uri: https://openminds.ebrains.eu/vocab/software
  class_uri: https://openminds.ebrains.eu/computation/Environment
  description: Structured information on the computer system or set of systems in
    which a computation is deployed and executed.
  title: Environment
