Environment:
  attributes:
    configuration:
      slot_uri: https://openminds.ebrains.eu/vocab/configuration
    description:
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/description
    hardware:
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/hardware
    id:
      identifier: true
      required: true
      slot_uri: schema:identifier
    name:
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/name
    software:
      list_elements_unique: true
      multivalued: true
      range: SoftwareVersion
      slot_uri: https://openminds.ebrains.eu/vocab/software
  class_uri: https://openminds.ebrains.eu/computation/Environment
  description: Structured information on the computer system or set of systems in
    which a computation is deployed and executed.
