LaunchConfiguration:
  attributes:
    argument:
      multivalued: true
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/argument
    description:
      description: Longer statement or account giving the characteristics of someone
        or something.
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/description
    environmentVariable:
      range: PropertyValueList
      slot_uri: https://openminds.ebrains.eu/vocab/environmentVariable
    executable:
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/executable
    id:
      identifier: true
      required: true
      slot_uri: schema:identifier
    name:
      description: Word or phrase that constitutes the distinctive designation of
        a being or thing.
      range: string
      slot_uri: https://openminds.ebrains.eu/vocab/name
  class_uri: https://openminds.ebrains.eu/computation/LaunchConfiguration
  description: Structured information about the launch of a computational process.
  title: Launch configuration
