LaunchConfiguration:
  class_uri: https://openminds.ebrains.eu/computation/LaunchConfiguration
  description: Structured information about the launch of a computational process.
  slot_usage:
    executable:
      required: true
  slots:
  - id
  - argument
  - description
  - environmentVariable
  - executable
  - name
  title: Launch configuration
