ProductAccessibility:
  class_uri: https://openminds.ebrains.eu/controlledTerms/ProductAccessibility
  description: null
  slot_usage:
    name:
      required: true
  slots:
  - id
  - definition
  - description
  - name
  - ontologyIdentifier
  title: Product accessibility
