Project:
  attributes:
    coordinator:
      description: Legal person who organizes the collaborative work of people or
        groups.
      list_elements_unique: true
      multivalued: true
      range: Consortium
      slot_uri: https://openminds.ebrains.eu/vocab/coordinator
    description:
      description: Longer statement or account giving the characteristics of someone
        or something.
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/description
    fullName:
      description: Whole, non-abbreviated name of something or somebody.
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/fullName
    hasPart:
      list_elements_unique: true
      multivalued: true
      range: ValidationTest
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/hasPart
    homepage:
      description: Main website of something or someone.
      range: Uri
      slot_uri: https://openminds.ebrains.eu/vocab/homepage
    id:
      identifier: true
      required: true
      slot_uri: schema:identifier
    shortName:
      description: Shortened or fully abbreviated name of something or somebody.
      range: string
      required: true
      slot_uri: https://openminds.ebrains.eu/vocab/shortName
  class_uri: https://openminds.ebrains.eu/core/Project
  description: Structured information on a research project.
  title: Project
