Configuration:
  class_uri: https://openminds.ebrains.eu/core/Configuration
  description: Structured information about the properties or parameters of an entity
    or process.
  slot_usage:
    configuration:
      range: string
      required: true
    format:
      range: ContentType
      required: true
    lookupLabel:
      range: string
  slots:
  - id
  - configuration
  - format
  - lookupLabel
  title: Configuration
