Service:
  class_uri: https://openminds.ebrains.eu/controlledTerms/Service
  description: null
  slot_usage:
    name:
      required: true
  slots:
  - id
  - definition
  - description
  - interlexIdentifier
  - knowledgeSpaceLink
  - name
  - preferredOntologyIdentifier
  - synonym
  title: Service
