SoftwareApplicationCategory:
  class_uri: https://openminds.ebrains.eu/controlledTerms/SoftwareApplicationCategory
  description: Structured information on the category of the software application.
  slot_usage:
    definition:
      range: string
    description:
      range: string
    interlexIdentifier:
      range: Uri
    knowledgeSpaceLink:
      range: Uri
    name:
      range: string
      required: true
    preferredOntologyIdentifier:
      range: Uri
    synonym:
      list_elements_unique: true
      multivalued: true
      range: string
  slots:
  - id
  - definition
  - description
  - interlexIdentifier
  - knowledgeSpaceLink
  - name
  - preferredOntologyIdentifier
  - synonym
  title: Software application category
